### ISSUE TITLE
Social Media Icons not showing

### ISSUE THREAD

**Issue by abhaysharma** [esca0035/portfolio#3]
@abhaysharma sorry for tagging you again, I have another issue. I added the icons for my social media, and they were showing, and everything was good, but now they aren't showing, I tried everything I even deleted them and put them again but they won't show anymore. 
<img width="1552" alt="Screenshot 2023-12-11 at 13 23 10" src="https://github.com/esca0035/portfolio/assets/133021484/8de1084c-7a32-43a1-b413-7989a128d4c0">

_Originally posted by @esca0035 in https://github.com/esca0035/portfolio/issues/2#issuecomment-1850636579_

**Comment by abhaysharma** [comment]
@esca0035 please push your recent code up so I can see what the issue is. The version you have on GitHub has the icons working.

**Comment by esca0035** [comment]
@abhaysharma Done, I pushed it. Thank you!

**Comment by abhaysharma** [comment]
@esca0035 on `line:217` in your css you will need to add `color: #997ABE !important;`
